# This workflow will build a Swift project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-swift

name: Automation Test

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: macos-14

    steps:
    - uses: actions/checkout@v4
    - uses: maxim-lobanov/setup-xcode@v1
      with:
        xcode-version: '15.2'
    - name: Build with the release configurations
      run: swift build -c release -v
    - name: Tests on iPhone 15 Pro (iOS 17.2) Simulator with release configurations
      run: xcodebuild 
           -scheme 'PersianJustify' 
           -sdk iphonesimulator 
           -destination 'platform=iOS Simulator,name=iPhone 15 Pro,OS=17.2' 
           test
    - name: Lint
        run: |
          set -o pipefail
          swiftlint lint --strict --quiet | sed -E 's/^(.*):([0-9]+):([0-9]+): (warning|error|[^:]+): (.*)/::\4 title=Lint error,file=\1,line=\2,col=\3::\5\n\1:\2:\3/'
